# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kurir' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'
  use_frameworks!
  
  pod 'Mobilex', :path => '../Mobilex'
  pod 'MobileSDK', :git => 'https://crazybeanstudio@bitbucket.org/crazybeanstudio/mobile-sdk-ios.git', :tag => '1.0.0'
  pod 'Swinject'
end
